tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-low": "#f2f4f6",
                "on-secondary-container": "#5e6369",
                "primary": "#004fa8",
                "tertiary-container": "#626b75",
                "tertiary": "#4a535c",
                "tertiary-fixed-dim": "#bec7d3",
                "secondary-fixed": "#dee3e9",
                "primary-container": "#0366d6",
                "inverse-primary": "#adc6ff",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#adc6ff",
                "surface": "#f8f9fb",
                "inverse-on-surface": "#eff1f3",
                "on-primary": "#ffffff",
                "on-primary-container": "#e5ebff",
                "background": "#f8f9fb",
                "tertiary-fixed": "#dae3ef",
                "on-error": "#ffffff",
                "on-surface": "#191c1e",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#004493",
                "on-background": "#191c1e",
                "outline": "#727785",
                "on-tertiary-fixed-variant": "#3f4851",
                "on-tertiary-fixed": "#141c25",
                "outline-variant": "#c2c6d6",
                "surface-variant": "#e0e3e5",
                "error": "#ba1a1a",
                "surface-container": "#eceef0",
                "surface-bright": "#f8f9fb",
                "on-surface-variant": "#424753",
                "secondary": "#5a5f65",
                "surface-container-high": "#e6e8ea",
                "surface-tint": "#005bc0",
                "surface-container-highest": "#e0e3e5",
                "on-secondary-fixed": "#171c21",
                "primary-fixed": "#d8e2ff",
                "secondary-fixed-dim": "#c2c7cd",
                "on-secondary": "#ffffff",
                "on-primary-fixed": "#001a41",
                "surface-dim": "#d8dadc",
                "secondary-container": "#dce0e7",
                "inverse-surface": "#2d3133",
                "on-tertiary-container": "#e3ecf8",
                "on-secondary-fixed-variant": "#42474d",
                "error-container": "#ffdad6",
                "on-tertiary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "xl": "32px",
                "sm": "8px",
                "xs": "4px",
                "base": "4px",
                "md": "16px",
                "gutter": "16px",
                "lg": "24px",
                "margin": "24px"
            },
            "fontFamily": {
                "body-lg": ["Inter", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "h2": ["Inter", "sans-serif"],
                "h1": ["Inter", "sans-serif"],
                "code": ["monospace"],
                "h3": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"]
            },
            "fontSize": {
                "body-lg": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
                "label-md": ["12px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "h2": ["24px", {"lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "h1": ["32px", {"lineHeight": "1.25", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "code": ["13px", {"lineHeight": "1.45", "letterSpacing": "0", "fontWeight": "400"}],
                "h3": ["20px", {"lineHeight": "1.25", "letterSpacing": "0", "fontWeight": "600"}],
                "body-md": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}]
            }
        }
    }
}
